package com.joymain.jecs.bd.model;
// Generated 2016-1-15 15:25:47 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * JbdTravelPointAllPK generated by hbm2java
 */

public class JbdTravelPointAllPK  implements java.io.Serializable {


    // Fields    

    private BigDecimal fyear;
    private String userCode;


    // Constructors

    /** default constructor */
    public JbdTravelPointAllPK() {
    }

    
    /** full constructor */
    public JbdTravelPointAllPK(BigDecimal fyear, String userCode) {
        this.fyear = fyear;
        this.userCode = userCode;
    }
    

   
    // Property accessors
    /**       
     *      *            @hibernate.id
     *             generator-class="assigned"
     *         
     *                @hibernate.property
     *                 column="F_YEAR"
     *             
     */

    public BigDecimal getFyear() {
        return this.fyear;
    }
    
    public void setFyear(BigDecimal fyear) {
        this.fyear = fyear;
    }
    /**       
     *      *            @hibernate.id
     *             generator-class="assigned"
     *         
     *                @hibernate.property
     *                 column="USER_CODE"
     *             
     */

    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JbdTravelPointAllPK) ) return false;
		 JbdTravelPointAllPK castOther = ( JbdTravelPointAllPK ) other; 
         
		 return ( (this.getFyear()==castOther.getFyear()) || ( this.getFyear()!=null && castOther.getFyear()!=null && this.getFyear().equals(castOther.getFyear()) ) )
 && ( (this.getUserCode()==castOther.getUserCode()) || ( this.getUserCode()!=null && castOther.getUserCode()!=null && this.getUserCode().equals(castOther.getUserCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFyear() == null ? 0 : this.getFyear().hashCode() );
         result = 37 * result + ( getUserCode() == null ? 0 : this.getUserCode().hashCode() );
         return result;
   }   





}
