package cn.p.dt.union;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Feb 16 13:06:46 CST 2011
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://dt.p.cn/union/", name = "PartnerRegServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PartnerRegServiceSoap {

    @RequestWrapper(localName = "NewAccount", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.NewAccount")
    @ResponseWrapper(localName = "NewAccountResponse", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.NewAccountResponse")
    @WebMethod(operationName = "NewAccount", action = "http://dt.p.cn/union/NewAccount")
    public void newAccount(
        @WebParam(name = "authStr", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String authStr,
        @WebParam(name = "regData", targetNamespace = "http://dt.p.cn/union/")
        cn.p.dt.union.DZhongmai regData,
        @WebParam(mode = WebParam.Mode.INOUT, name = "msg", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.String> msg,
        @WebParam(mode = WebParam.Mode.OUT, name = "NewAccountResult", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.Boolean> newAccountResult
    );

    @RequestWrapper(localName = "ModifyPwd", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.ModifyPwd")
    @ResponseWrapper(localName = "ModifyPwdResponse", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.ModifyPwdResponse")
    @WebMethod(operationName = "ModifyPwd", action = "http://dt.p.cn/union/ModifyPwd")
    public void modifyPwd(
        @WebParam(name = "authStr", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String authStr,
        @WebParam(name = "userCode", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String userCode,
        @WebParam(name = "oldPwd", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String oldPwd,
        @WebParam(name = "newPwd", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String newPwd,
        @WebParam(mode = WebParam.Mode.INOUT, name = "msg", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.String> msg,
        @WebParam(mode = WebParam.Mode.OUT, name = "ModifyPwdResult", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.Boolean> modifyPwdResult
    );

    @RequestWrapper(localName = "ModifyLevel", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.ModifyLevel")
    @ResponseWrapper(localName = "ModifyLevelResponse", targetNamespace = "http://dt.p.cn/union/", className = "cn.p.dt.union.ModifyLevelResponse")
    @WebMethod(operationName = "ModifyLevel", action = "http://dt.p.cn/union/ModifyLevel")
    public void modifyLevel(
        @WebParam(name = "authStr", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String authStr,
        @WebParam(name = "userCode", targetNamespace = "http://dt.p.cn/union/")
        java.lang.String userCode,
        @WebParam(name = "newLevel", targetNamespace = "http://dt.p.cn/union/")
        int newLevel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "msg", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.String> msg,
        @WebParam(mode = WebParam.Mode.OUT, name = "ModifyLevelResult", targetNamespace = "http://dt.p.cn/union/")
        javax.xml.ws.Holder<java.lang.Boolean> modifyLevelResult
    );
}
