package com.integracoreb2b;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Mar 21 11:15:47 CST 2011
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://www.integracoreb2b.com/", name = "IncomingOrdersSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IncomingOrdersSoap {

    @WebResult(name = "OrderImportResult", targetNamespace = "http://www.integracoreb2b.com/")
    @RequestWrapper(localName = "OrderImport", targetNamespace = "http://www.integracoreb2b.com/", className = "com.integracoreb2b.OrderImport")
    @ResponseWrapper(localName = "OrderImportResponse", targetNamespace = "http://www.integracoreb2b.com/", className = "com.integracoreb2b.OrderImportResponse")
    @WebMethod(operationName = "OrderImport", action = "http://www.integracoreb2b.com/OrderImport")
    public com.integracoreb2b.OrderResults orderImport(
        @WebParam(name = "Orders", targetNamespace = "http://www.integracoreb2b.com/")
        com.integracoreb2b.ArrayOfOrder orders
    );
}
