
/*
 * 
 */

package com.integracoreb2b;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Mar 21 11:15:47 CST 2011
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "IncomingOrders", 
                  wsdlLocation = "http://www.integracoreb2b.com/IntCore/IncomingOrders.asmx?wsdl",
                  targetNamespace = "http://www.integracoreb2b.com/") 
public class IncomingOrders extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.integracoreb2b.com/", "IncomingOrders");
    public final static QName IncomingOrdersSoap = new QName("http://www.integracoreb2b.com/", "IncomingOrdersSoap");
    public final static QName IncomingOrdersSoap12 = new QName("http://www.integracoreb2b.com/", "IncomingOrdersSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://www.integracoreb2b.com/IntCore/IncomingOrders.asmx?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://www.integracoreb2b.com/IntCore/IncomingOrders.asmx?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IncomingOrders(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IncomingOrders(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IncomingOrders() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IncomingOrdersSoap
     */
    @WebEndpoint(name = "IncomingOrdersSoap")
    public IncomingOrdersSoap getIncomingOrdersSoap() {
        return super.getPort(IncomingOrdersSoap, IncomingOrdersSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncomingOrdersSoap
     */
    @WebEndpoint(name = "IncomingOrdersSoap")
    public IncomingOrdersSoap getIncomingOrdersSoap(WebServiceFeature... features) {
        return super.getPort(IncomingOrdersSoap, IncomingOrdersSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns IncomingOrdersSoap
     */
    @WebEndpoint(name = "IncomingOrdersSoap12")
    public IncomingOrdersSoap getIncomingOrdersSoap12() {
        return super.getPort(IncomingOrdersSoap12, IncomingOrdersSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncomingOrdersSoap
     */
    @WebEndpoint(name = "IncomingOrdersSoap12")
    public IncomingOrdersSoap getIncomingOrdersSoap12(WebServiceFeature... features) {
        return super.getPort(IncomingOrdersSoap12, IncomingOrdersSoap.class, features);
    }

}
